version: '3'

services:
  ziurtagiriak:
    build:
      context: .
      dockerfile: ZiurtagiriakAPP/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DIRECCION_CONTRATO_ZIURTAGIRIAK: "0x4D5D0548f967218c56696a0A550C11439ACd53DE"
      CLAVE_PRIVADA_CREADOR_CONTRATO_ZIURTAGIRIAK: "0xe6a413b0e7813bec1877175e1260502405828b53e83a36e5f9df1966821a402d"
    networks:
      - besu_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - ziurtagiriak
    networks:
      - besu_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blockchain
      MYSQL_USER: blockchain
      MYSQL_PASSWORD: blockchain
    ports:
      - "3306:3306"
    networks:
      - besu_network
    volumes:
      - ./ZiurtagiriakAPP/blockchain-dump.sql:/docker-entrypoint-initdb.d/blockchain-dump.sql
      - db_data:/var/lib/mysql

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true

volumes:
  db_data:
